name: Flutter Web

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write # Required for checkout
  pages: write # Required for deploying to GitHub Pages
  id-token: write # Required for OpenID Connect (if you use it, good practice to include)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build web --release --base-href="/animal_chess/"

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }} # or your default branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
